# Dependencies
markdown:		kramdown
highlighter:	rouge

# Permalinks
permalink:		none

# Setup
title:			Gerard M
tagline:		'UCSD Math-CS'
description:    'UCSD Math-CS'
url:			GerardMaggiolino.github.io

author:
  name:			'Gerard Maggiolino'

paginate:		10

# Custom vars
version:		1.0.0

github:         
  repo:			https://github.com/GerardMaggiolino/
    
plugins:		
    - jekyll-paginate
    - jekyll-seo-tag
